name: harmony-gdal-adapter
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.10
  - pip
  # For packaging, and testing
  - setuptools_scm
  - pytest
  - pytest-cov
  # For running
  - gdal
  - libgdal-hdf5
  - pystac
  - pip:
      - -r requirements.txt
      - -r requirements-static.txt
