name: Check Conda Environment Matches Pixi

on: push

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.10.2
      - name: Check Conda Environment Matches
        run: |
          pixi workspace export conda-environment --from-lock-file > environment.yml
          git diff --exit-code || (echo "Error: Conda environment does not match Pixi lockfile. Run `pixi workspace export conda-environment --from-lock-file > environment.yml` and commit the changes." && exit 1)
