name: Update Conda Environment from Pixi

on:
  push:
    paths: ["pixi.lock"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-conda-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.10.2
      - name: Generate environment.yaml from pixi.lock
        run: |
          pixi workspace export conda-environment -n harmony-gdal-adapter --from-lock-file > environment.yml
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add environment.yml
          if ! git diff --cached --quiet; then
            git commit -m "chore: update enviroment.yaml from CI workflow [skip ci]"
            git push origin HEAD:${{ github.head_ref || github.ref_name }}
          else
            echo "No changes to commit"
          fi
